##########
# collectionbuilder-sheets
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-sheets
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-sheets

##########
# SITE SETTINGS
#
# title of site appears in banner
title: University of Oregon Nosatsu Collection
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A Curated and Compressed Sample of the Wider University of Oregon Nosatsu Collection
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Our collection is themed around the Asian art on display at the JSMA and held by the school, especially the nōsatsu votive slips kept in Special Collections. We aim to provide an easily-viewable sampler of various slips, with attendant metadata, to make further research into the slips easier for students and other academics.Exact provenance data on many of the slips is unclear, and while it turned out that tracing it was beyond the scope of this class project our hope is that our initial research can help lay the groundwork for a more extensive future project. Also, the website that currently displays the nōsatsu is extremely slow, and hard to navigate. We thought that it’d be useful to have a fast site that helps display smaller, curated examples from the larger archive, from a variety of sources within it. The importance of the theme above suggests two primary groups that might be interested in this collection. The first are those who want easy access to data related to the nōsatsu strips to perform further research on provenance and other related topics. The second is students of various fields, such as Art History and Asian Studies, who want a convenient source without having to slog through the sluggish database system."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Niko T, Casey C, Jesse M, and Jacob G.

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection 
# This will be the full URL to your CSV file or relative path + filename of CSV in this repository 
# e.g. relative path "/assets/demo-metadata.csv"
# e.g. published google sheet "https://docs.google.com/spreadsheets/d/e/2PACX-1vSn7AA-cbsXT3_nNUGftc1ab-CKXOJHMQCIENeR9NHElbyI9_qA99o0-HNZdG04v-M2_N21bUe_krQQ/pub?output=csv"
# e.g. on GitHub use the raw link "https://raw.githubusercontent.com/CollectionBuilder/collectionbuilder-sample-data/main/psychiana_cbdemo_gh.csv"
metadata-csv: https://docs.google.com/spreadsheets/d/e/2PACX-1vTLHhUiKhia97TEzNqEp6CUpBMUpw5n4NZfvdaS5TNMYGFaSjwwqPlcm6rWbmUgGZ1bGAx3FPnSZPTD/pub?output=csv

##########
# Site/Organization Branding 
# 
# Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# dev mode turns on ability to change metadata
development-mode: true
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
